# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://blog.bhe.me
title: BheHonTyu' Blogging
subtitle:
author: histmaxft
simple_search: http://google.com.hk/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: mfthits#gmail.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, custom/asides/douban.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: hitsmaxft
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: hitsmaxft
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user: hitsmaxft
delicious_count: 3

# Disqus Comments
disqus_short_name: bhehontyublogging
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: "UA-42604344-1"

# Facebook Like
facebook_like: false


#Douban
douban_user: hitsmaxft #Cannot be blank, either you douban id (eight-digit number) or your douban account name
douban_people: hitsmaxft
douban_apikey: #YOu can leave it blank
douban_show:  #The type of display ,include: dolist(doing),wishlist(want to),collection(seen), Leave it blank to random
douban_display_category: book|movie #The type of display ,include:book music blog movie, format: xx|yy|zz (for example movie|book|music), Leave it blank to All
douban_display: random #What for display, Other options: favorite(good),Leave it blank to display last added
douban_total_show: 5 #How many to display
douban_percolumn: 3 #How many per column 
douban_img_style: small #The size of the content pictures, Leave it blank to small
douban_hidelogo: true #Leave it blank to false
douban_hideself:  true #Leave it blank to false
